# Generated by Django 4.2.1 on 2023-05-15 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_newarrivals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newarrivals',
            name='image_url',
            field=models.CharField(max_length=2000),
        ),
    ]
