# Generated by Django 4.2.1 on 2023-05-15 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_newarrivals_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('stock', models.IntegerField()),
                ('image_url', models.CharField(max_length=2083)),
            ],
        ),
        migrations.DeleteModel(
            name='NewArrivals',
        ),
        migrations.DeleteModel(
            name='offer',
        ),
        migrations.DeleteModel(
            name='Products',
        ),
    ]
