# Generated by Django 4.2.1 on 2023-05-15 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_delete_newarrivals_delete_offer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewArrival',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image_url', models.CharField(max_length=2000)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(max_length=255)),
                ('availability', models.BooleanField(default=True)),
                ('product_id', models.CharField(max_length=255)),
                ('arrival_date', models.DateField()),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('brand', models.CharField(max_length=255)),
            ],
        ),
    ]
